name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make test
