name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: pwd; ls -al
      - name: my_script
        run: ./myscript.sh
